services:
  camundaEngine:
    image: moritz148/camunda7experiment:engine
    container_name: camundaEngine
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://camundaEngine:8080/engine-rest/engine"]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - camunda-platform

  c7experiment:
    image: moritz148/camunda7experiment:benchmark
    container_name: c7experiment
    restart: "no"
    depends_on:
      camundaEngine:
        condition: service_healthy
    networks:
      - camunda-platform


networks:
  camunda-platform:
    driver: bridge