spring:
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true

camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest

server:
  port: 8081

logging:
  level:
    root: WARN